### ISSUE TITLE
Design: 각 기기별로 깨지는 현상 수정

### ISSUE THREAD

**Issue by SuKyeong2002** [2024GanzithonPYTHON/14_Ganzi_Frontend#15]
## ✨ About Issue ✨
각 기기 크기별로 맞지 않는 부분 수정

<br>

## ✅ Todo
- [ ] 메인홈 화면 UI 수정
- [ ] 로그인/회원가입 화면 UI 수정
- [ ] 프로젝트 생성 화면 UI 수정
- [ ] 마이페이지 화면 UI 수정
