### ISSUE TITLE
Feat: 메인홈 기능 구현 

### ISSUE THREAD

**Issue by SuKyeong2002** [2024GanzithonPYTHON/14_Ganzi_Frontend#19]
## ✨ About Issue ✨
로그인, 회원가입 기능을 구현합니다.

<br>

## ✅ Todo
- [x] 로그인 기능 구현 (토큰 받기)
- [x] 로그아웃 기능 구현
- [x] 회원가입 아이디 중복확인 기능 구현
- [x] 회원가입 닉네임 중복확인 기능 구현
- [x] 회원가입 기능 구현  (토큰 받기)
