### ISSUE TITLE
Feat: 마이페이지 기능 구현

### ISSUE THREAD

**Issue by SuKyeong2002** [2024GanzithonPYTHON/14_Ganzi_Frontend#21]
## ✨ About Issue ✨
마이페이지 기능을 구현합니다.

<br>

## ✅ Todo
- [x] 유저 정보 조회 기능 구현 
- [ ] 유저 정보 수정 기능 구현 
- [ ] 회원 탈퇴 기능 구현
